/** Shared Clerk dark-theme styling for Steer (light text on dark surfaces). */
export const steerClerkAppearance = {
  variables: {
    colorBackground: "#1a1a1a",
    // Current Clerk API
    colorForeground: "#e4e4e4",
    colorMutedForeground: "#a0a0a0",
    colorInput: "#252525",
    colorInputForeground: "#e4e4e4",
    colorPrimary: "#e4e4e4",
    colorPrimaryForeground: "#141414",
    // Legacy aliases (older Clerk builds)
    colorText: "#e4e4e4",
    colorTextSecondary: "#a0a0a0",
    colorInputBackground: "#252525",
    colorInputText: "#e4e4e4",
    colorTextOnPrimaryBackground: "#141414",
    colorDanger: "#f07070",
    colorSuccess: "#3ecf8e",
    colorNeutral: "#a0a0a0",
    borderRadius: "0.375rem",
  },
  elements: {
    rootBox: "w-full !text-[#e4e4e4]",
    card: "bg-[#1a1a1a] border border-[#2b2b2b] shadow-none !text-[#e4e4e4]",
    cardBox: "!text-[#e4e4e4]",
    main: "!text-[#e4e4e4]",
    headerTitle: "!text-[#e4e4e4]",
    headerSubtitle: "!text-[#a0a0a0]",
    formHeaderTitle: "!text-[#e4e4e4]",
    formHeaderSubtitle: "!text-[#a0a0a0]",
    socialButtonsBlockButton:
      "bg-[#252525] border border-[#2b2b2b] !text-[#e4e4e4] hover:bg-[#2e2e2e]",
    socialButtonsBlockButtonText: "!text-[#e4e4e4]",
    socialButtonsProviderIcon: "opacity-90",
    dividerLine: "bg-[#2b2b2b]",
    dividerText: "!text-[#6e6e6e]",
    formFieldLabel: "!text-[#a0a0a0]",
    formFieldInput:
      "bg-[#252525] border border-[#2b2b2b] !text-[#e4e4e4] placeholder:!text-[#6e6e6e] focus:border-[#4d9fff]",
    formFieldInputShowPasswordButton: "!text-[#a0a0a0] hover:!text-[#e4e4e4]",
    formFieldHintText: "!text-[#6e6e6e]",
    formFieldSuccessText: "!text-[#3ecf8e]",
    formFieldErrorText: "!text-[#f07070]",
    formFieldWarningText: "!text-[#e4e4e4]",
    formButtonPrimary:
      "bg-[#e4e4e4] !text-[#141414] hover:bg-white border-0",
    formButtonReset: "!text-[#a0a0a0] hover:!text-[#e4e4e4]",
    footerActionText: "!text-[#a0a0a0]",
    footerActionLink: "!text-[#e4e4e4] hover:!text-white",
    footer: "!text-[#a0a0a0]",
    identityPreviewText: "!text-[#e4e4e4]",
    identityPreviewEditButton: "!text-[#a0a0a0] hover:!text-[#e4e4e4]",
    identityPreviewEditButtonIcon: "!text-[#a0a0a0]",
    alternativeMethodsBlockButton:
      "bg-[#252525] border border-[#2b2b2b] !text-[#e4e4e4] hover:bg-[#2e2e2e]",
    alternativeMethodsBlockButtonText: "!text-[#e4e4e4]",
    otpCodeFieldInput:
      "bg-[#252525] border border-[#2b2b2b] !text-[#e4e4e4]",
    navbar: "bg-[#1a1a1a] border-[#2b2b2b]",
    navbarButton: "!text-[#a0a0a0] hover:!text-[#e4e4e4]",
    navbarButtonIcon: "!text-[#a0a0a0]",
    pageScrollBox: "bg-[#1a1a1a] !text-[#e4e4e4]",
    page: "bg-[#1a1a1a] !text-[#e4e4e4]",
    profileSection: "border-[#2b2b2b]",
    profileSectionTitle: "!text-[#e4e4e4]",
    profileSectionTitleText: "!text-[#e4e4e4]",
    profileSectionContent: "!text-[#a0a0a0]",
    profileSectionPrimaryButton:
      "bg-[#252525] border border-[#2b2b2b] !text-[#e4e4e4] hover:bg-[#2e2e2e]",
    badge: "bg-[#252525] !text-[#a0a0a0] border border-[#2b2b2b]",
    avatarBox: "border border-[#2b2b2b]",
    accordionTriggerButton: "!text-[#e4e4e4] hover:bg-[#252525]",
    accordionContent: "bg-[#141414] !text-[#e4e4e4]",
    userPreviewMainIdentifier: "!text-[#e4e4e4]",
    userPreviewSecondaryIdentifier: "!text-[#6e6e6e]",
    userButtonPopoverCard: "bg-[#1a1a1a] border border-[#2b2b2b] shadow-xl",
    userButtonPopoverActionButton:
      "!text-[#e4e4e4] hover:bg-[#252525]",
    userButtonPopoverActionButtonText: "!text-[#e4e4e4]",
    userButtonPopoverActionButtonIcon: "!text-[#a0a0a0]",
    userButtonPopoverFooter: "hidden",
  },
} as const;
